### ISSUE TITLE
List of central vue libraries with their Vue3 compatibility status 

### ISSUE THREAD

**Issue by elevatebart** [blacksonic/awesome-vue-3#30]
## Objective:

Guide developers in their migration from vue 2 to vue 3, specifically in their dependencies

## Contents

- name of library
- name of the branch where the vue 3 work has started
- how to install the vue 3 compatible version
- The GH issue where the progress is tracked
- if the author(s) has started documenting how to migrate from vue 2 to vue 3, add a link to the docs.

| Framework                                         | Branch name                                                                                | npm install           | GH Issue #                                                             | Docs |
| ------------------------------------------------- | ------------------------------------------------------------------------------------------ | --------------------- | ---------------------------------------------------------------------- | ---- |
| [NuxtJS](https://nuxtjs.org/)                     | -                                                                                          | -                     | [5708](https://github.com/nuxt/nuxt.js/issues/5708)                    |      |
| [Gridsome](https://gridsome.org/)                 | [vue-next](https://github.com/gridsome/gridsome/tree/vue-next)                             | -                     | [1289](https://github.com/gridsome/gridsome/issues/1289)               |      |
| [Quasar](https://quasar.dev/)                     | [vue3-work](https://github.com/quasarframework/quasar/tree/vue3-work)                      | -                     | [7836](https://github.com/quasarframework/quasar/issues/7836)          |      |
| [vuepress](https://vuepress.vuejs.org/)           | [vuepress-next](https://github.com/vuepress/vuepress-next) (other repo)                    | -                     | [2550](https://github.com/vuejs/vuepress/issues/2550)                  |      |
| [NativeScript-Vue](https://nativescript-vue.org/) | [rigor789/nativescript-vue-next](https://github.com/rigor789/nativescript-vue-next) (fork) | nativescript-vue@next | [583](https://github.com/nativescript-vue/nativescript-vue/issues/583) |      |

| Library                                     | Branch name                                                                                 | npm install  | GH Issue #                                                         | Docs                                                                                |
| ------------------------------------------- | ------------------------------------------------------------------------------------------- | ------------ | ------------------------------------------------------------------ | ----------------------------------------------------------------------------------- |
| [vuetify](https://vuetifyjs.com/)           | [next](https://github.com/vuetifyjs/vuetify/tree/next)                                      | -            | -                                                                  | [Notion board](https://www.notion.so/Vuetify-Next-edf8fdb074eb4643a7196aaf8e5d5cad) |
| [bootstrap-vue](https://bootstrap-vue.org/) | [lamebear/vue3](https://github.com/lamebear/bootstrap-vue/tree/vue3/) (fork)                | -            | [5196](https://github.com/bootstrap-vue/bootstrap-vue/issues/5196) |                                                                                     |
| [buefy](https://buefy.org/)                 | -                                                                                           | -            | [2505](https://github.com/buefy/buefy/issues/2505)                 |                                                                                     |
| [chakra-ui](https://vue.chakra-ui.com/)     | -                                                                                           | -            | [116](https://github.com/chakra-ui/chakra-ui-vue/issues/116)       |                                                                                     |
| [element-ui](https://element.eleme.io/)     | [element-plus](https://github.com/element-plus/element-plus/) (other repo)                  | element-plus | [20061](https://github.com/ElemeFE/element/issues/20061)           |                                                                                     |
| [inkline](https://inkline.io/)              | -                                                                                           | -            | [207](https://github.com/inkline/inkline/issues/207)               |                                                                                     |
| [oruga](https://oruga.io/)                  | [oruga-next](https://github.com/oruga-ui/oruga/tree/develop/packages/oruga-next) (monorepo) | oruga-next   |                                                                    |                                                                                     |

| Tool                                                    | Branch name                                                                                   | npm install       | GH Issue #                                                                              | Docs                                            |
| ------------------------------------------------------- | --------------------------------------------------------------------------------------------- | ----------------- | --------------------------------------------------------------------------------------- | ----------------------------------------------- |
| [Vue Formulate](https://vueformulate.com/)              | [axwalker/support-vue-3](https://github.com/axwalker/vue-formulate/tree/support-vue-3) (fork) | -                 | [198](https://github.com/wearebraid/vue-formulate/issues/198)                           |                                                 |
| [@testing-library/vue](https://testing-library.com/vue) | [vue3](https://github.com/testing-library/vue-testing-library/tree/vue3)                      | -                 | -                                                                                       |                                                 |
| [vue-apollo](https://apollo.vuejs.org)                  | [v4](https://github.com/vuejs/vue-apollo/tree/v4)                                             | -                 | [1011](https://github.com/vuejs/vue-apollo/issues/1011)                                 | [V4 docs (Vue 3)](https://v4.apollo.vuejs.org/) |
| [vue-meta](https://vue-meta.nuxtjs.org/)                | [next](https://github.com/nuxt/vue-meta/tree/next)                                            | -                 | [558](https://github.com/nuxt/vue-meta/issues/558)                                      |                                                 |
| [vue-axe](axe.vue-a11y.com/)                            | [vue-axe-next](https://github.com/vue-a11y/vue-axe-next) (other repo)                         | vue-axe@beta      | [1](https://github.com/vue-a11y/vue-axe-next/issues/1)                                  | [demo site](https://vue-axe-next.surge.sh/)     |
| [vee-validate](https://vee-validate.logaretm.com/)      | [next](https://github.com/logaretm/vee-validate/tree/next)                                    | vee-validate@next | [2670](https://github.com/logaretm/vee-validate/issues/2670)                            |                                                 |
| [vuelidate](https://vuelidate.js.org/)                  | [next](https://github.com/vuelidate/vuelidate/tree/next)                                      | vuelidate@next    | [2.0](https://github.com/vuelidate/vuelidate/issues?q=is%3Aissue+is%3Aopen+label%3A2.0) | [V2 docs](https://vuelidate-next.netlify.app/)  |

| Workbench                                               | Branch name                                                            | npm install | GH Issue #                                                             | Docs |
| ------------------------------------------------------- | ---------------------------------------------------------------------- | ----------- | ---------------------------------------------------------------------- | ---- |
| [Storybook](https://storybook.js.org/)                  | -                                                                      | -           | [10654](https://github.com/storybookjs/storybook/issues/10654)         |      |
| [Vue Styleguidist](https://vue-styleguidist.github.io/) | [next](https://github.com/vue-styleguidist/vue-styleguidist/tree/next) | -           | [997](https://github.com/vue-styleguidist/vue-styleguidist/issues/997) |      |

| Component                                             | Branch name                                                                    | npm install            | GH Issue #                                                     | Docs |
| ----------------------------------------------------- | ------------------------------------------------------------------------------ | ---------------------- | -------------------------------------------------------------- | ---- |
| [vue-multiselect](https://vue-multiselect.js.org/)    | -                                                                              | -                      | [1291](https://github.com/shentao/vue-multiselect/issues/1291) |      |
| [vue2-leaflet](https://vue2-leaflet.netlify.app/)     | [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet) (other repo)         | -                      | [455](https://github.com/vue-leaflet/Vue2Leaflet/issues/455)   |      |
| [tiptap](https://tiptap.dev/)                         | -                                                                              | -                      | [735](https://github.com/ueberdosis/tiptap/issues/735)         |      |
| [tsParticles](https://particles.matteobruni.it/)      | [vue3](https://github.com/matteobruni/tsparticles/tree/master/components/vue3) | particle.vue3          | -                                                              |      |
| [vue-live](http://vue-live.surge.sh/)                 | [next](https://github.com/vue-styleguidist/vue-live/tree/next)                 | vue-live@next          | [54](https://github.com/vue-styleguidist/vue-live/issues/54)   |      |
| [vue-prism-editor](https://prism-editor.netlify.app/) | [feature/next](https://github.com/koca/vue-prism-editor/tree/feature/next)     | vue-prism-editor@alpha | [90](https://github.com/koca/vue-prism-editor/issues/90)       |      |

**Comment by Akryum** [comment]
https://awesomejs.dev/for/vue/ also has a `vue version 3` tag in blue

**Comment by elevatebart** [comment]
Thank you @Akryum,

That really is helpful.

What does the `vue version 3` tag mean on awesome vue?
In other words, is there a way to see the definition of such a tag?

- Is the library is compatible with vue 3 in its latest instance?
- Does it have a version compatible with vue 3? on what channel? how to install it?
- Is this is the distribution of the library that you should take that contain the vue 3 version?

I am hoping to start answering this kind of question here for starters. 
Though, I am not sure this table should live here for too long.

@blacksonic what do you think?

**Comment by ktquez** [comment]
Hi @elevatebart 
`vue-axe` has a version for Vue 3 in this [vue-axe-next](https://github.com/vue-a11y/vue-axe-next) repository.

**Comment by elevatebart** [comment]
thank you @ktquez,

Adding now

**Comment by elevatebart** [comment]
There you go, added now. I hope it's good enough.

**Comment by matteobruni** [comment]
tsParticles Vue component has a 3.x version: You can see them [here](https://github.com/matteobruni/tsparticles)

The packages are: `particles.vue` and `particles.vue3`

**Comment by elevatebart** [comment]
Thank you @matteobruni 

I will add it too.

**Comment by blacksonic** [comment]
Thats an awesome idea! Can you make a PR out of it?

**Comment by ktquez** [comment]
Thanks @elevatebart

**Comment by elevatebart** [comment]
@blacksonic I thought about it last night and there are advantages to issues:
- Comments are easy
- Github creates deep links between repositories when one puts a link to an issue 
  - The issue linked gets a reference to this issue
- Anybody (me in this case) can create it without the author's permission (Mouhahahaha !!! 😈😈 )

There are downsides as well:
- No pull request possible
- No suggestion template

**Comment by matteobruni** [comment]
> Thank you @matteobruni
> 
> I will add it too.
> 
> Would you mind adding a link to:
> 
> * How you track progress (GH issue, docs)?

Progress of?

> * The npmjs channel where people can install the Vue 3 version

The packages are both on `npmjs`: `particles.vue` for 2.x and `particles.vue3` for 3.x

> * The branch where it is developed

They are both available on `master` but the new features branch is `dev`

> * If applicable the documentation on how to upgrade from Vue 2 to Vue 3?

**Vue 2.x docs**
https://github.com/matteobruni/tsparticles/blob/master/components/vue/README.md

**Vue 3.x docs**
https://github.com/matteobruni/tsparticles/blob/master/components/vue3/README.md

**Comment by elevatebart** [comment]
Thank you @matteobruni I added tsParticle to the list. 

But I don't feel good about it.

What would you imagine be the story of a user of `particle.vue` for vue 2 would want to migrate his work to vue 3?
I think I was not clear. I do not want to create a list of packages that have a vue 3 version. 
I am trying to help devs migrate their codebase to vue 3 by checking their dependencies and providing useful links.

Do you still think tsParticle should be in such a list?

**Comment by matteobruni** [comment]
This is a good point, I'll create a doc that explains how to migrate to the Vue 3.x version.

Since Vue 2.x is more popular for now I'd like to support the 2.x version for some time.

**Comment by elevatebart** [comment]
Thank you @matteobruni 

Agreed, keep me posted. When the migration docs are ready I can add them to this list.

**Comment by matteobruni** [comment]
@elevatebart the migration instructions are here: https://github.com/matteobruni/tsparticles/blob/master/components/vue3/README.md#migrating-from-vue-2x-to-vue-3x

**Comment by blacksonic** [comment]
Newcomers don't go straight to the issues section I think, it remains hidden to many people

**Comment by elevatebart** [comment]
@blacksonic you are absolutely right, discoverability is the key.

I don't like the idea of such a small independent piece of data being dissolved in the bigger Readme.
I would not even know where to put it.

I will ask around to people that are trying the migration what they would rather have.

The place I would like to find it when migrating would probably be in the vue v3 docs. 
@NataliaTepluhina, @phanan, @bencodezen 

What do you think?

**Comment by elevatebart** [comment]
I will stop updating this issue,
All future updates will be done here

vuejs/awesome-vue#3544

**Comment by eeerrrttty** [comment]
will nativescript be integrated ? So quasar 2 will have native build ?

**Comment by elevatebart** [comment]
Hello @eeerrrttty You might wan to go ask those questions to the maintainers of those 2 libraries.
The column issue will point you to the right place to start the conversation.
